debug: false

mob-limits:
  # The entity type to apply the limit
  # https://jd.papermc.io/paper/1.21.11/org/bukkit/entity/EntityType.html
  pillager:
    # Radius (in blocks) to check for nearby entities
    radius: 36
    # Maximum number of entities allowed within the radius
    count: 100
    # List of spawn reasons to apply this limit
    # Reference: https://jd.papermc.io/paper/1.21.11/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
    # Multiple spawn reasons can be specified.
    # If empty [], all spawn reasons are apply.
    reasons:
      - NATURAL
  zombified_piglin:
    radius: 50
    count: 100
    reasons:
      - NETHER_PORTAL